// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: execution.proto
package com.kasper.MessageCatalogService.protos;

public final class Execution {
  private Execution() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface executionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:execution)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string symbol = 1;</code>
     */
    boolean hasSymbol();
    /**
     * <code>required string symbol = 1;</code>
     */
    java.lang.String getSymbol();
    /**
     * <code>required string symbol = 1;</code>
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>required string market = 2;</code>
     */
    boolean hasMarket();
    /**
     * <code>required string market = 2;</code>
     */
    java.lang.String getMarket();
    /**
     * <code>required string market = 2;</code>
     */
    com.google.protobuf.ByteString
        getMarketBytes();

    /**
     * <code>required float price = 3;</code>
     */
    boolean hasPrice();
    /**
     * <code>required float price = 3;</code>
     */
    float getPrice();

    /**
     * <code>required float quantity = 4;</code>
     */
    boolean hasQuantity();
    /**
     * <code>required float quantity = 4;</code>
     */
    float getQuantity();

    /**
     * <code>required int64 executionEpoch = 5;</code>
     */
    boolean hasExecutionEpoch();
    /**
     * <code>required int64 executionEpoch = 5;</code>
     */
    long getExecutionEpoch();

    /**
     * <code>required string stateSymbol = 6;</code>
     */
    boolean hasStateSymbol();
    /**
     * <code>required string stateSymbol = 6;</code>
     */
    java.lang.String getStateSymbol();
    /**
     * <code>required string stateSymbol = 6;</code>
     */
    com.google.protobuf.ByteString
        getStateSymbolBytes();
  }
  /**
   * Protobuf type {@code execution}
   */
  public  static final class execution extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:execution)
      executionOrBuilder {
    // Use execution.newBuilder() to construct.
    private execution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private execution() {
      symbol_ = "";
      market_ = "";
      price_ = 0F;
      quantity_ = 0F;
      executionEpoch_ = 0L;
      stateSymbol_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private execution(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              symbol_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              market_ = bs;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              price_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              quantity_ = input.readFloat();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              executionEpoch_ = input.readInt64();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              stateSymbol_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Execution.internal_static_execution_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Execution.internal_static_execution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Execution.execution.class, Execution.execution.Builder.class);
    }

    private int bitField0_;
    public static final int SYMBOL_FIELD_NUMBER = 1;
    private volatile java.lang.Object symbol_;
    /**
     * <code>required string symbol = 1;</code>
     */
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string symbol = 1;</code>
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          symbol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string symbol = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MARKET_FIELD_NUMBER = 2;
    private volatile java.lang.Object market_;
    /**
     * <code>required string market = 2;</code>
     */
    public boolean hasMarket() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string market = 2;</code>
     */
    public java.lang.String getMarket() {
      java.lang.Object ref = market_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          market_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string market = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMarketBytes() {
      java.lang.Object ref = market_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        market_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private float price_;
    /**
     * <code>required float price = 3;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float price = 3;</code>
     */
    public float getPrice() {
      return price_;
    }

    public static final int QUANTITY_FIELD_NUMBER = 4;
    private float quantity_;
    /**
     * <code>required float quantity = 4;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float quantity = 4;</code>
     */
    public float getQuantity() {
      return quantity_;
    }

    public static final int EXECUTIONEPOCH_FIELD_NUMBER = 5;
    private long executionEpoch_;
    /**
     * <code>required int64 executionEpoch = 5;</code>
     */
    public boolean hasExecutionEpoch() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 executionEpoch = 5;</code>
     */
    public long getExecutionEpoch() {
      return executionEpoch_;
    }

    public static final int STATESYMBOL_FIELD_NUMBER = 6;
    private volatile java.lang.Object stateSymbol_;
    /**
     * <code>required string stateSymbol = 6;</code>
     */
    public boolean hasStateSymbol() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string stateSymbol = 6;</code>
     */
    public java.lang.String getStateSymbol() {
      java.lang.Object ref = stateSymbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stateSymbol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string stateSymbol = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStateSymbolBytes() {
      java.lang.Object ref = stateSymbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stateSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSymbol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMarket()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExecutionEpoch()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStateSymbol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, market_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, quantity_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, executionEpoch_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stateSymbol_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, market_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, quantity_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, executionEpoch_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, stateSymbol_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Execution.execution)) {
        return super.equals(obj);
      }
      Execution.execution other = (Execution.execution) obj;

      boolean result = true;
      result = result && (hasSymbol() == other.hasSymbol());
      if (hasSymbol()) {
        result = result && getSymbol()
            .equals(other.getSymbol());
      }
      result = result && (hasMarket() == other.hasMarket());
      if (hasMarket()) {
        result = result && getMarket()
            .equals(other.getMarket());
      }
      result = result && (hasPrice() == other.hasPrice());
      if (hasPrice()) {
        result = result && (
            java.lang.Float.floatToIntBits(getPrice())
            == java.lang.Float.floatToIntBits(
                other.getPrice()));
      }
      result = result && (hasQuantity() == other.hasQuantity());
      if (hasQuantity()) {
        result = result && (
            java.lang.Float.floatToIntBits(getQuantity())
            == java.lang.Float.floatToIntBits(
                other.getQuantity()));
      }
      result = result && (hasExecutionEpoch() == other.hasExecutionEpoch());
      if (hasExecutionEpoch()) {
        result = result && (getExecutionEpoch()
            == other.getExecutionEpoch());
      }
      result = result && (hasStateSymbol() == other.hasStateSymbol());
      if (hasStateSymbol()) {
        result = result && getStateSymbol()
            .equals(other.getStateSymbol());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSymbol()) {
        hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
        hash = (53 * hash) + getSymbol().hashCode();
      }
      if (hasMarket()) {
        hash = (37 * hash) + MARKET_FIELD_NUMBER;
        hash = (53 * hash) + getMarket().hashCode();
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPrice());
      }
      if (hasQuantity()) {
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getQuantity());
      }
      if (hasExecutionEpoch()) {
        hash = (37 * hash) + EXECUTIONEPOCH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getExecutionEpoch());
      }
      if (hasStateSymbol()) {
        hash = (37 * hash) + STATESYMBOL_FIELD_NUMBER;
        hash = (53 * hash) + getStateSymbol().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Execution.execution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Execution.execution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Execution.execution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Execution.execution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Execution.execution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Execution.execution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Execution.execution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Execution.execution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Execution.execution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Execution.execution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Execution.execution prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code execution}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:execution)
        Execution.executionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Execution.internal_static_execution_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Execution.internal_static_execution_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Execution.execution.class, Execution.execution.Builder.class);
      }

      // Construct using Execution.execution.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        symbol_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        market_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        quantity_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        executionEpoch_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        stateSymbol_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Execution.internal_static_execution_descriptor;
      }

      public Execution.execution getDefaultInstanceForType() {
        return Execution.execution.getDefaultInstance();
      }

      public Execution.execution build() {
        Execution.execution result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Execution.execution buildPartial() {
        Execution.execution result = new Execution.execution(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.symbol_ = symbol_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.market_ = market_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.executionEpoch_ = executionEpoch_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.stateSymbol_ = stateSymbol_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Execution.execution) {
          return mergeFrom((Execution.execution)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Execution.execution other) {
        if (other == Execution.execution.getDefaultInstance()) return this;
        if (other.hasSymbol()) {
          bitField0_ |= 0x00000001;
          symbol_ = other.symbol_;
          onChanged();
        }
        if (other.hasMarket()) {
          bitField0_ |= 0x00000002;
          market_ = other.market_;
          onChanged();
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasExecutionEpoch()) {
          setExecutionEpoch(other.getExecutionEpoch());
        }
        if (other.hasStateSymbol()) {
          bitField0_ |= 0x00000020;
          stateSymbol_ = other.stateSymbol_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSymbol()) {
          return false;
        }
        if (!hasMarket()) {
          return false;
        }
        if (!hasPrice()) {
          return false;
        }
        if (!hasQuantity()) {
          return false;
        }
        if (!hasExecutionEpoch()) {
          return false;
        }
        if (!hasStateSymbol()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Execution.execution parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Execution.execution) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object symbol_ = "";
      /**
       * <code>required string symbol = 1;</code>
       */
      public boolean hasSymbol() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            symbol_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public Builder clearSymbol() {
        bitField0_ = (bitField0_ & ~0x00000001);
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        symbol_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object market_ = "";
      /**
       * <code>required string market = 2;</code>
       */
      public boolean hasMarket() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string market = 2;</code>
       */
      public java.lang.String getMarket() {
        java.lang.Object ref = market_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            market_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string market = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMarketBytes() {
        java.lang.Object ref = market_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          market_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string market = 2;</code>
       */
      public Builder setMarket(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        market_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string market = 2;</code>
       */
      public Builder clearMarket() {
        bitField0_ = (bitField0_ & ~0x00000002);
        market_ = getDefaultInstance().getMarket();
        onChanged();
        return this;
      }
      /**
       * <code>required string market = 2;</code>
       */
      public Builder setMarketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        market_ = value;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>required float price = 3;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float price = 3;</code>
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>required float price = 3;</code>
       */
      public Builder setPrice(float value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float price = 3;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0F;
        onChanged();
        return this;
      }

      private float quantity_ ;
      /**
       * <code>required float quantity = 4;</code>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float quantity = 4;</code>
       */
      public float getQuantity() {
        return quantity_;
      }
      /**
       * <code>required float quantity = 4;</code>
       */
      public Builder setQuantity(float value) {
        bitField0_ |= 0x00000008;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float quantity = 4;</code>
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        quantity_ = 0F;
        onChanged();
        return this;
      }

      private long executionEpoch_ ;
      /**
       * <code>required int64 executionEpoch = 5;</code>
       */
      public boolean hasExecutionEpoch() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 executionEpoch = 5;</code>
       */
      public long getExecutionEpoch() {
        return executionEpoch_;
      }
      /**
       * <code>required int64 executionEpoch = 5;</code>
       */
      public Builder setExecutionEpoch(long value) {
        bitField0_ |= 0x00000010;
        executionEpoch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 executionEpoch = 5;</code>
       */
      public Builder clearExecutionEpoch() {
        bitField0_ = (bitField0_ & ~0x00000010);
        executionEpoch_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object stateSymbol_ = "";
      /**
       * <code>required string stateSymbol = 6;</code>
       */
      public boolean hasStateSymbol() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string stateSymbol = 6;</code>
       */
      public java.lang.String getStateSymbol() {
        java.lang.Object ref = stateSymbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stateSymbol_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string stateSymbol = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStateSymbolBytes() {
        java.lang.Object ref = stateSymbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stateSymbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string stateSymbol = 6;</code>
       */
      public Builder setStateSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stateSymbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string stateSymbol = 6;</code>
       */
      public Builder clearStateSymbol() {
        bitField0_ = (bitField0_ & ~0x00000020);
        stateSymbol_ = getDefaultInstance().getStateSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>required string stateSymbol = 6;</code>
       */
      public Builder setStateSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stateSymbol_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:execution)
    }

    // @@protoc_insertion_point(class_scope:execution)
    private static final Execution.execution DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Execution.execution();
    }

    public static Execution.execution getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<execution>
        PARSER = new com.google.protobuf.AbstractParser<execution>() {
      public execution parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new execution(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<execution> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<execution> getParserForType() {
      return PARSER;
    }

    public Execution.execution getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_execution_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_execution_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017execution.proto\"y\n\texecution\022\016\n\006symbol" +
      "\030\001 \002(\t\022\016\n\006market\030\002 \002(\t\022\r\n\005price\030\003 \002(\002\022\020\n" +
      "\010quantity\030\004 \002(\002\022\026\n\016executionEpoch\030\005 \002(\003\022" +
      "\023\n\013stateSymbol\030\006 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_execution_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_execution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_execution_descriptor,
        new java.lang.String[] { "Symbol", "Market", "Price", "Quantity", "ExecutionEpoch", "StateSymbol", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
